# English internationalization file for XLingDoc
# Copyright (c) 2026 SIL International
# This software is licensed under the LGPL, version 2.1 or later 
# (http://www.gnu.org/licenses/lgpl-2.1.html) 
program.name=XLingDoc
# menu items
menu.about=_About XLingDoc
# TODO: fix the following menu items when we create them 
menu.backgroundandlineparameters=_Background and line parameters
menu.changeinterfacelanguage=_Change the interface language
menu.copy=_Copy
menu.cut=Cu_t
menu.descriptionfontsize=_Font size for tree description symbols
menu.drawastype=_Draw tree as you type
menu.drawtree=_Draw Tree
menu.edit=_Edit
menu.exit=E_xit
menu.file=_File
menu.format=F_ormat
menu.help=_Help
menu.keyboards=Set keyboards
menu.lexicalfont=_Lexical font
menu.new=_New Tree
menu.open=_Open Tree...
menu.paste=_Paste
menu.quickreferenceguide=_Quick Reference Guide
menu.redo=_Redo
menu.restarttree=_Erase Description; Start All Over
menu.save=_Save Tree
menu.saveas=Save Tree _As...
menu.saveaspng=Save tree as ._png file
menu.saveassvg=Save tree as .s_vg file
menu.savetreeparameters=Save the current tree parameters to use for _new tree diagrams
menu.settings=_Settings
menu.showmatchingparendelay=Delay to use when showing matching _parentheses
menu.showmatchingparenwitharrowkeys=_Show matching parenthesis with arrow keys
menu.tree=_Tree
menu.treespacingparameters=Tree _spacing parameters
menu.undo=_Undo
menu.usedashedlinesforsplitinfixedbase=Use dashed lines for split infixed base
menu.userdocumentation=User _Documentation
menu.userighttoleftorientation=Draw tree _right-to-left
menu.view=_View

# About dialog
about.header=About XLingDox
about.content=A Philippine style word tree drawing program.\n(DiagSap is short for "diagramang sapin-sapin" which is Tagalog for "layered diagram.")\n\nVersion: {0}\n\n© 2021-2026 SIL International\nThis software is licensed under the LGPL, version 2.1 or later\n(http://www.gnu.org/licenses/lgpl-2.1.html)

#File Open/Save As dialog; import/export
file.filterdescription=DiagSap files
file.new=Save New Tree As
file.requiresavecontent=Please save the file.
file.requiresaveheader=Important!

#Choose Interface Language dialog
dialog.chooseinterfacelanguage=Choose Interface Language
dialog.chooselanguage=Choose language:

#Font selector dialog
fontselector.dialogtitle=Select Font
fontselector.dialogheadertext=Select Font
fontselector.font=Font
fontselector.sample=Sample Text
fontselector.size=Size
fontselector.style=Style
 
# labels
label.areyousure=Are you sure you want to do this?
label.browse=Browse
label.cancel=Cancel
label.close=Close
label.createnewtree=Create a new tree
label.date=Date
label.description=Description
label.enterdescription=Enter tree description here
label.filename=File Name
label.help=Help
label.key=Begin a tree node = ( \u23A5 End a tree node = ) \u23A5 Begin an infix = < \u23A5 End an infix = > \u23A5 Infix index = \\1, \\2 ... \\9
label.name=Name
label.no=No
label.ok=OK
label.openexistingtree=Open existing tree
label.useflattree=Flat
label.yes=Yes

# file loading/saving
file.asktosavecontent=Do you want to save any changes?
file.asktosaveheader=Changes may have been made.
file.chooseanoption=Choose an option:
file.error.load.content=Could not load data from file:\n
file.error.load.header=Could not load data
file.error.save.content=Could not save data to file:\n
file.error.save.header=Could not save data
file.error=Error
file.initiallynotfound=Apparently this program has not been run before.

# Miscellaneous
misc.niycontent=Not implemented yet.
misc.niyheader=Sorry

# Tooltips
tooltip.copy=Copy   Ctrl+C
tooltip.cut=Cut   Ctrl+X
tooltip.drawtree=Draw Tree   Ctrl+D
tooltip.new=New Tree   Ctrl+N
tooltip.open=Open Tree   Ctrl+O
tooltip.paste=Paste   Ctrl+V
tooltip.save=Save Tree   Ctrl+S
tooltip.saveaspng=Save tree as .png file
tooltip.saveassvg=Save tree as .svg file
tooltip.showmatchingparenwitharrowkeys=Show matching parenthesis with arrow keys

#Keyboard dialog
keyboarddialog.lexical=Lexical
keyboarddialog.syntagmeme=Tree description symbols
keyboarddialog.title=Keyboards

# Element chooser names
element.text=(text)

